baseURL: https://jonnyspicer.com
languageCode: en-gb
title: Jonny Spicer
defaultContentLanguage: en
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
cannonifyURLs: true
summaryLength: 10
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  category: categories
  series: series
  tags: tags
permalinks:
  blog: /:section/:title
  essay: /:title
params:
  author: Jonny Spicer
  ogimage: "/img/og.png"
  github: https://github.com/jonnyspicer
  twitter: https://twitter.com/jjspicer
  sitename: Jonny Spicer
  description: Jonny Spicer is a founder, software engineer, blogger, runner, climber and music lover, and this is his personal site
menu:
  main:
    - name: "All In"
      url: "https://allinlabs.io"
      weight: 3
      target: "_blank"
server:
  headers:
    - for: /**
      values:
        Access-Control-Allow-Origin: "*"
