baseURL: https://jonnyspicer.com
languageCode: en-gb
title: Jonny Spicer
description: Jonny Spicer is a software engineer, blogger, runner, climber and music lover, and this is his personal site.
defaultContentLanguage: en
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
cannonifyURLs: true
summaryLength: 10
taxonomies:
  category: categories
  series: series
  tags: tags
permalinks:
  blog: /:section/:title
params:
  author: Jonny Spicer
  ogimage: "/img/og.png"
  github: https://github.com/jonnyspicer
  twitter: https://twitter.com/jjspicer
  sitename: Jonny Spicer